#!/bin/bash

g++ main.cpp -lX11 -lglog -o .window_manager;

XEPHYR=$(whereis -b Xephyr | cut -f2 -d' ')
xinit ./.xinitrc -- \
    "$XEPHYR" \
        :100 \
        -ac \
        -screen 800x600 \
        -host-cursor
